name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # Use your default branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0  # Use Ruby version 3.0 or higher

    - name: Install dependencies
      run: |
        bundle install  # This installs the dependencies from the Gemfile

    - name: Build the site
      run: bundle exec jekyll build  # Build the site using Jekyll

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site  # Ensure this points to the folder where Jekyll outputs the site
